#!/usr/bin/env bash
# install.sh — one-line installer for the tracker.
#
# Usage (after the repo is published):
#   curl -fsSL https://raw.githubusercontent.com/<USER>/<REPO>/main/install.sh | bash
#
# What this script does:
#   1. Checks you're on macOS and have Python 3.11+ + git
#   2. Clones the repo into ~/.local/share/tracker
#   3. Creates a venv inside that folder, installs all dependencies
#   4. Creates a tiny wrapper at /usr/local/bin/track (or ~/.local/bin/track)
#   5. Tells you exactly what manual steps remain (ActivityWatch, Chrome ext, API key)
#
# Re-running this script is safe — it pulls the latest version.

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
REPO_URL="${TRACKER_REPO_URL:-https://github.com/toogoodmanny/tracker.git}"
INSTALL_DIR="${TRACKER_INSTALL_DIR:-$HOME/.local/share/tracker}"
BIN_NAME="track"

# Output helpers
red()    { printf "\033[31m%s\033[0m\n" "$*"; }
green()  { printf "\033[32m%s\033[0m\n" "$*"; }
yellow() { printf "\033[33m%s\033[0m\n" "$*"; }
blue()   { printf "\033[34m%s\033[0m\n" "$*"; }
bold()   { printf "\033[1m%s\033[0m\n" "$*"; }

err_exit() {
    red "ERROR: $1"
    exit 1
}

# ---------------------------------------------------------------------------
# 1. Pre-flight checks
# ---------------------------------------------------------------------------
bold "==> Tracker installer"
echo

if [[ "$(uname)" != "Darwin" ]]; then
    err_exit "This tool currently supports macOS only. (You're on $(uname).)"
fi

if ! command -v git >/dev/null 2>&1; then
    err_exit "git is not installed.

Install it by running this in Terminal:
    xcode-select --install

Then re-run this installer."
fi

# Find Python 3.11+
PYTHON_BIN=""
for candidate in python3.13 python3.12 python3.11 python3; do
    if command -v "$candidate" >/dev/null 2>&1; then
        ver=$("$candidate" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
        major=$(echo "$ver" | cut -d. -f1)
        minor=$(echo "$ver" | cut -d. -f2)
        if [[ "$major" -ge 3 && "$minor" -ge 11 ]]; then
            PYTHON_BIN=$(command -v "$candidate")
            break
        fi
    fi
done

if [[ -z "$PYTHON_BIN" ]]; then
    err_exit "Python 3.11 or newer is required.

Install it by running this in Terminal:
    /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\"
    brew install python@3.13

Then re-run this installer."
fi

green "    OK — found $($PYTHON_BIN --version) at $PYTHON_BIN"

# ---------------------------------------------------------------------------
# 2. Clone or update the repo
# ---------------------------------------------------------------------------
echo
bold "==> Fetching the tracker code"

mkdir -p "$(dirname "$INSTALL_DIR")"

if [[ -d "$INSTALL_DIR/.git" ]]; then
    blue "    Updating existing install at $INSTALL_DIR"
    git -C "$INSTALL_DIR" fetch --quiet
    git -C "$INSTALL_DIR" reset --hard origin/main --quiet
else
    blue "    Cloning into $INSTALL_DIR"
    git clone --quiet "$REPO_URL" "$INSTALL_DIR"
fi
green "    OK"

# ---------------------------------------------------------------------------
# 3. Create venv + install deps
# ---------------------------------------------------------------------------
echo
bold "==> Creating Python environment + installing dependencies"
echo "    (this can take 1-2 minutes the first time)"

VENV_DIR="$INSTALL_DIR/.venv"

if [[ ! -d "$VENV_DIR" ]]; then
    "$PYTHON_BIN" -m venv "$VENV_DIR"
fi

"$VENV_DIR/bin/pip" install --quiet --upgrade pip
"$VENV_DIR/bin/pip" install --quiet -e "$INSTALL_DIR[macos]"

green "    OK"

# ---------------------------------------------------------------------------
# 4. Install the `track` shim
# ---------------------------------------------------------------------------
echo
bold "==> Installing the 'track' command"

# Prefer /usr/local/bin if writable, else ~/.local/bin
if [[ -w "/usr/local/bin" ]]; then
    BIN_DIR="/usr/local/bin"
elif [[ -d "/usr/local/bin" ]] && sudo -n true 2>/dev/null; then
    BIN_DIR="/usr/local/bin"
    SUDO="sudo"
else
    BIN_DIR="$HOME/.local/bin"
    mkdir -p "$BIN_DIR"
fi
SUDO="${SUDO:-}"

SHIM_PATH="$BIN_DIR/$BIN_NAME"

cat > /tmp/track-shim <<EOF
#!/usr/bin/env bash
# tracker shim — auto-generated by install.sh
exec "$VENV_DIR/bin/track" "\$@"
EOF
chmod +x /tmp/track-shim
$SUDO mv /tmp/track-shim "$SHIM_PATH"

green "    Installed: $SHIM_PATH"

# Warn if BIN_DIR isn't on PATH
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    yellow "    Note: $BIN_DIR is not on your PATH."
    echo "    Add this line to your ~/.zshrc:"
    echo "        export PATH=\"\$PATH:$BIN_DIR\""
fi

# ---------------------------------------------------------------------------
# 5. Next steps
# ---------------------------------------------------------------------------
echo
green "==> Done. Now finish the manual setup:"
echo
bold "    1. Install ActivityWatch (free desktop app)"
echo "       Download: https://activitywatch.net"
echo "       Open it once after installing — it lives in your menu bar."
echo
bold "    2. Get an Anthropic API key"
echo "       https://console.anthropic.com/api-keys"
echo "       Have it ready to paste in the next step."
echo
bold "    3. Run the personalization wizard:"
echo "       track setup"
echo
bold "    4. Load the Chrome extension (optional but recommended)"
echo "       Folder to load: $INSTALL_DIR/chrome_extension"
echo "       Open chrome://extensions → toggle Developer mode → Load unpacked"
echo
bold "    5. Start tracking your first day:"
echo "       track start"
echo
echo "If you get stuck, see HELP.md in $INSTALL_DIR"
echo "or paste $INSTALL_DIR/HELP_PROMPT.md into Claude and ask for help."
echo
